---
title: "Fix kappa choose m"
author: "Jonathan Rosenblatt"
date: "1/1/2015"
output: pdf_document
---
## Fix N

```{r fix N simulate}
library(InformationAndInference)
source('choose_m.R')
```



```{r OLS fix N frame and plot}
# load('RData/MSEs_choose_m.6.RData')
MSEs.framed.000 <- frameMSEs(MSEs.000, configurations.000)
.lwd <- 1
.lty <- 3
.lwd.error <- 0.5
.lty.error <- 1
.point.size <- 3
.point.size.error <- 0
.scale <- scale_y_log10()

# Second order fixed-p bias approxiamtion
MSEs.framed.000 %<>% mutate(error.asympt=biasOLS_Fixp())

plot.0001 <- plotMSEs2(MSEs.framed.000, '(a) OLS Bias', robust=NA, legend.position='none', jitter=0, line=TRUE, fix='Np', center='bias.mean', lty=.lty, lwd=.lwd, lwd.error=.lwd.error, lty.error = .lty.error, point.size = .point.size, point.size.error = .point.size.error)
plot.0001

# High dim MSE approximation
MSEs.framed.000 %<>% mutate(kappa=p/n)
MSEs.framed.000$error.asympt <-  apply(MSEs.framed.000, 1, function(x) 
  ApproxMSE_OLS_highdim2(kappa=x[['kappa']], m=x[['m']], sigma.sq = x[['sigma']]^2))

plot.0002 <- plotMSEs2(MSEs.framed.000, '(c) OLS MSE- high-dim', robust=NA, legend.position='none', jitter=0, line=TRUE, fix='Np', center='MSE',  lty=.lty, lwd=.lwd, lwd.error=.lwd.error, lty.error = .lty.error, point.size = .point.size, point.size.error = .point.size.error, scale.y = .scale)
plot.0002

# Second order fixed-p MSE approximation
MSEs.framed.000 %<>% mutate(kappa=p/n)
MSEs.framed.000$error.asympt <-  apply(MSEs.framed.000, 1, function(x) 
  ApproxMSE_OLS_fixp2(n=x[['n']], p=x[['p']], m=x[['m']], sigma.sq = x[['sigma']]^2))

plot.0003 <- plotMSEs2(MSEs.framed.000, '(b) OLS MSE- second order fixed-p', robust=NA, legend.position='none', jitter=0, line=TRUE, fix='Np', center='MSE', lty=.lty, lwd=.lwd,  lwd.error=.lwd.error, lty.error = .lty.error, point.size = .point.size, point.size.error = .point.size.error, scale.y = .scale)
plot.0003
```


```{r fix N OLS plot}
directory <- "~/workspace/ParalSimulate/output/"
the.file <-paste(directory, "choose_m_OLS_1.pdf", sep='')
pdf(file=the.file, onefile = FALSE, paper = "special", width=8, height=8)

plot.0001 <- plot.0001 +
  theme(legend.position=c(0.08, 0.5), legend.key.size=unit(5,"mm")) 

grid.arrange(plot.0001, plot.0003, plot.0002, ncol=1)
dev.off()
```






```{r Ridge fix N}
# load('RData/MSEs_choose_m_ridge.6.RData')
MSEs.framed.001<- frameMSEs(MSEs.001, configurations.001, coordinate = 1)
MSEs.framed.001 %>% select(replications, bias.single, p) %>% head



# Second order Ridge bias
MSEs.framed.001$error.asympt <-  apply(MSEs.framed.001, 1, function(x) 
  biasMeanRidge_Fixp(N=x[['N']], p = x[['p']], m=x[['m']], lambda = x[['lambda']], beta = x[['beta.star']]))

plot.0011 <- plotMSEs2(MSEs.framed.001, '(a) Ridge bias', robust=NA, legend.position='none',  jitter=0, line=TRUE, fix='Np', center='bias.mean', lty = .lty, lwd=.lwd, lty.error = .lty.error, lwd.error = .lwd.error,  point.size = .point.size, point.size.error = .point.size.error)
plot.0011

# Second order Ridge MSE
MSEs.framed.001$error.asympt <-  apply(MSEs.framed.001, 1, function(x) 
  ApproxMSE_Ridge_fixp2(n=x[['n']], p=x[['p']], m=x[['m']], lambda = x[['lambda']], beta = x[['beta']], sigma.sq = x[['sigma']]^2))

plot.0012 <- plotMSEs2(MSEs.framed.001, '(b) Ridge second order MSE ', robust=NA, legend.position='none',  jitter=0, line=TRUE, fix='Np', center='MSE', lty = .lty, lwd=.lwd, lty.error = .lty.error, lwd.error = .lwd.error,  point.size = .point.size, point.size.error = .point.size.error, scale.y = scale_y_log10())
plot.0012
```


```{r fix N Ridge plot}
directory <- "~/workspace/ParalSimulate/output/"
the.file <-paste(directory, "choose_m_Ridge_1.pdf", sep='')
pdf(file=the.file, onefile = FALSE, paper = "special", width=8, height=8)

plot.0011 <- plot.0011 +
  theme(legend.position=c(0.08, 0.45), legend.key.size=unit(5,"mm"))

grid.arrange(plot.0011, plot.0012, ncol=1)
dev.off()
```



```{r fix N export seperate plots}
directory <- "~/workspace/ParalSimulate/output/"
the.file <-paste(directory, "choose_m_1_%3d.eps", sep='')
postscript(file=the.file, onefile = FALSE, horizontal = FALSE, paper = "special", width=8, height=8)
grid.arrange(plot.000, plot.0001, plot.0010, plot.0011, ncol=2)
# plot.000
# plot.0001
# plot.0010
# plot.0011
dev.off()
```





```{r Arror approximations for OLS}
MSEs.framed.000 %<>% mutate(error.asympt=ApproxMSE_OLS_highdim2(kappa=kappa, m = m, sigma.sq = sigma^2))
plot.00001 <- plotMSEs2(MSEs.framed.000, '(a) OLS MSE HighDim 1', robust=NA, legend.position='none', jitter=0, line=TRUE, fix='Np', center='MSE')
plot.00001

MSEs.framed.000 %<>% mutate(error.asympt=ApproxMSE_OLS_highdim(kappa=kappa, m = m, sigma.sq = sigma^2))
plot.00002 <- plotMSEs2(MSEs.framed.000, '(b) OLS MSE HighDim 2', robust=NA, legend.position='none', jitter=0, line=TRUE, fix='Np', center='MSE')
plot.00002

MSEs.framed.000 %<>% mutate(error.asympt=ApproxMSE_OLS_fixp(n=n, p=p, m = m, sigma.sq = sigma^2))
plot.00003 <- plotMSEs2(MSEs.framed.000, '(c) OLS MSE Fix p', robust=NA, legend.position='none', jitter=0, line=TRUE, fix='Np', center='MSE')
plot.00003


# plot
the.file <-paste(directory, "choose_m_compare_OLS.pdf", sep='')
pdf(file=the.file, onefile = FALSE, paper = "special", width=8, height=8)
plot.00001 <- plot.00001 +
  theme(legend.position=c(0.2, 0.65), legend.key.size=unit(5,"mm"))
grid.arrange(plot.00001, plot.00002, plot.00003, ncol=2)
dev.off()
```






## Fix n:
```{r fix n split results}
# load(file='RData/MSEs_fix_p.1.RData') 

MSEs.framed <- frameMSEs(MSEs, configurations)

ols.ind <- sapply(MSEs.framed$model, function(x) isTRUE(all.equal(x, my.ols))) 
configurations[ols.ind,'name'] <- 'ols'
MSEs.framed.0 <- MSEs.framed[ols.ind,]
```

```{r fix n plot}
plot.001 <- plotMSEs2(MSEs.framed.0, '(b) Fix n', robust=NA, legend.position='right', y.lim=c(0,3), jitter=0, line=TRUE, fix='n')
plot.001
```

```{r fix n export plot}
directory <- "~/workspace/ParalSimulate/output/"
the.file <-paste(directory, "choose_m_1.pdf", sep='')
pdf(file=the.file, onefile = FALSE, paper = "special", width=8, height=8)
grid.arrange(plot.000, plot.001)
dev.off()
```

TODO: 
- Add theoretical bias line.
- Simulate bias and not MSE if lines do not overlap.
- Simulate Ridge regression with bias lines.
