---
title: "Parallelization Simulation"
author: "Jonathan Rosenblatt"
date: "1/1/2015"
output: pdf_document
---

```{r make Configurations}
library(InformationAndInference)
.m <- c(1e1, 2e1, 4e1, 1e2)
.kappa <- 0.2
.n <- seq(4e1, 4e3, length.out=6)
.sigma <- 1e1
.beta.norm <- 1e0

## OLS
configurations.00 <- makeConfiguration(
  reps = 1e2, 
  m = .m, 
  n = .n , 
  kappa = .kappa, 
  lambda = NA, 
  sigma = .sigma, 
  model = my.ols, link = identity, 
  beta.maker = makeBetasDeterministic, 
  beta.norm = .beta.norm,
  beta.star.maker = BetaStarIdentity, 
  data.maker = makeRegressionData,
  name='ols') 
## Ridge
configurations.10 <- makeConfiguration(
  reps = 1e2,
  m = .m, 
  kappa = .kappa, 
  n = .n, 
  lambda=2,
  model = my.ridge, link = identity, sigma = .sigma, 
  beta.maker = makeBetasDeterministic, 
  beta.norm=.beta.norm, 
  beta.star.maker = BetaStarRidge,
  data.maker=makeRegressionData, 
  name='ridge') 
## Non Linear
configurations.30 <- makeConfiguration(
  reps = 5e2, 
  m = .m, 
  kappa = .kappa, 
  n = .n, 
  lambda = NA, 
  model = my.log.link, link = exp, sigma = 1, 
  beta.maker = makeBetasDeterministic, 
  beta.norm=.beta.norm, 
  beta.star.maker = BetaStarIdentity, 
  data.maker=makeRegressionData, 
  name='nls') 
## Logistic Regression
configurations.40<- makeConfiguration(
  reps = 2e2, 
  m = .m, 
  kappa = .kappa, 
  n = .n,
  lambda=NA,
  model = my.logistic, link = sigmoid, sigma = .sigma, 
  beta.maker = makeBetasDeterministic, 
  beta.norm=.beta.norm,
  beta.star.maker = BetaStarIdentity, 
  data.maker = makeClassificationData, 
  name='logistic') 
```


```{r run simulation}
source('fix_kappa_run.R')
```

```{r split results}
# load(file='RData/MSEs_fix_kappa.5RData') 

MSEs.framed.fix.kappa <- frameMSEs_fixKappa(MSEs.fix.kappa, configurations.fix.kappa)

MSEs.framed.00 <- MSEs.framed.fix.kappa %>% filter(name=='ols')
MSEs.framed.10 <- MSEs.framed.fix.kappa %>% filter(name=='ridge')
MSEs.framed.30 <- MSEs.framed.fix.kappa %>% filter(name=='nls')
MSEs.framed.40 <- MSEs.framed.fix.kappa %>% filter(name=='logistic')

MSEs.framed.00 %<>% mutate(truth=truthOLS(kappa=kappa, m=m)) 
```


```{r all_plots}
.ylim <- c(0.5,1.5)
.ylim2 <- c(0.5,30)

.jitter <- 100
plot.00 <- plotMSEs_fixKappa(MSEs.framed.00, '(a) OLS', legend.position='none', y.lim=.ylim)
plot.10 <- plotMSEs_fixKappa(MSEs.framed.10, '(b) Ridge', legend.position='none', y.lim=.ylim)
plot.30 <- plotMSEs_fixKappa(MSEs.framed.30, '(c) Non-Linear Least Squares', legend.position='none', y.lim=.ylim2)
plot.40 <- plotMSEs_fixKappa(MSEs.framed.40, '(d) Logistic Regression', legend.position='right', y.lim=.ylim2)

grid.arrange(plot.00, plot.10, plot.30, plot.40, ncol=2)
```


```{r export plot}
directory <- "~/workspace/ParalSimulate/output/"
the.file <-paste(directory, "highdim_asymptotics_1.pdf", sep='')
pdf(file=the.file, onefile = FALSE, paper = "special", width=8, height=8)
grid.arrange(plot.00, plot.10, plot.30, plot.40, ncol=2)
dev.off()
```


```{r export data}
flat.fix.kappa <- lapply(MSEs.fix.kappa, t) %>% do.call(rbind,.)

selected.configurations.fix.kappa <- configurations.fix.kappa %>% select(name,n,p,m,N,kappa,sigma)

repeated.configurations.fix.kappa <- NULL
for(i in 1:nrow(configurations.fix.kappa) ){
  repeated.configurations.fix.kappa <- rbind(
    repeated.configurations.fix.kappa, 
    rep.row(selected.configurations.fix.kappa[i,], 
            configurations.fix.kappa$replications[i]))
}
MSEs.boaz.fix.kappa <- cbind(repeated.configurations.fix.kappa, flat.fix.kappa) 
head(MSEs.boaz.fix.kappa)

write.csv(MSEs.boaz.fix.kappa %>% as.matrix, file='output/fix_kappa_raw.csv',col.names=TRUE)
```

