---
title: "Fix kappa choose m"
author: "Jonathan Rosenblatt"
date: "1/1/2015"
output: pdf_document
---
## Fix N
```{r fix N simulate}
# source('fix_kappa_choose_m.R')
```



```{r fix N frame and plot}
# load('RData/MSEs_choose_m.1.RData')
MSEs.framed.000 <- frameMSEs(MSEs.000, configurations.000)
MSEs.framed.000 %>% select(N,p) %>% table
plot.000 <- plotMSEs2(MSEs.framed.000, '(a) Fix N', robust=NA, legend.position='right', y.lim=c(0,3), jitter=0, line=TRUE, fix='Np')
plot.000
```

```{r fix N export plot}
directory <- "~/workspace/ParalSimulate/output/"
the.file <-paste(directory, "choose_m_1.pdf", sep='')
pdf(file=the.file, onefile = FALSE, paper = "special", width=8, height=8)
plot.000
dev.off()
```



## Fix n:
```{r fix n split results}
# load(file='RData/MSEs_fix_p.1.RData') 

MSEs.framed <- frameMSEs(MSEs, configurations)

ols.ind <- sapply(MSEs.framed$model, function(x) isTRUE(all.equal(x, my.ols))) 
configurations[ols.ind,'name'] <- 'ols'
MSEs.framed.0 <- MSEs.framed[ols.ind,]
```

```{r fix n plot}
plot.001 <- plotMSEs2(MSEs.framed.0, '(b) Fix n', robust=NA, legend.position='right', y.lim=c(0,3), jitter=0, line=TRUE, fix='n')
plot.001
```

```{r fix n export plot}
directory <- "~/workspace/ParalSimulate/output/"
the.file <-paste(directory, "choose_m_1.pdf", sep='')
pdf(file=the.file, onefile = FALSE, paper = "special", width=8, height=8)
grid.arrange(plot.000, plot.001)
dev.off()
```

TODO: 
- Add theoretical bias line.
- Simulate bias and not MSE if lines do not overlap.
- Simulate Ridge regression with bias lines.
