---
title: "Parallelization Simulation"
author: "Jonathan Rosenblatt"
date: "1/1/2015"
output: pdf_document
---

```{r Make configurations}
library(InformationAndInference)
.m <- c(1e1, 2e1, 4e1, 1e2)
.p <- 5e1
.n <- seq(4e1, 3e3, length.out=6)
.sigma <- 1e1
.lambda <- 1e-1
.beta.norm <- 1e0
.beta.maker <- makeBetasDeterministic

## OLS
configurations.0 <- makeConfiguration(
  reps = 2e2, 
  m = .m, p = .p, n = .n, lambda = NA, 
  model = my.ols, link = identity, sigma = .sigma, beta.norm = .beta.norm,
  beta.maker = .beta.maker, 
  beta.star.maker = BetaStarIdentity,
  data.maker=makeRegressionData,
  name='ols') 
## Ridge
configurations.1 <- makeConfiguration(
  reps = 5e1,
  m = .m, 
  p = .p, 
  n = .n, 
  lambda=.lambda,
  model = my.ridge, link = identity, sigma = .sigma, beta.norm = .beta.norm,
  beta.maker = .beta.maker, 
  beta.star.maker = BetaStarRidge,
  data.maker=makeRegressionData,
  name='ridge') 
## Non Linear
configurations.3 <- makeConfiguration(
  reps = 5e2, 
  m = .m, 
  p = .p, 
  n = .n, 
  lambda = NA, 
  model = my.log.link, link = exp, sigma = 1, beta.norm = .beta.norm,
  beta.maker = .beta.maker, 
  beta.star.maker = BetaStarIdentity, 
  data.maker=makeRegressionData,
  name='nls') 
## Logistic Regression
configurations.4<- makeConfiguration(
  reps = 5e2, 
  m = .m, 
  p = .p, 
  n = .n, 
  lambda = NA, 
  model = my.logistic, link = sigmoid, sigma = 1e1, beta.norm = .beta.norm,
  beta.maker = .beta.maker, beta.star.maker = BetaStarIdentity, 
  data.maker = makeClassificationData,
  name='logistic') 
```


```{r run simulation}
source('fix_p_run.R')
```

```{r split results}
load(file='RData/MSEs_fix_p.9.RData') 
library(InformationAndInference)

MSEs.framed <- frameMSEs(MSEs, configurations)

MSEs.framed.0 <- MSEs.framed %>% filter(name=='ols')
MSEs.framed.1 <- MSEs.framed %>% filter(name=='ridge')
MSEs.framed.3 <- MSEs.framed %>% filter(name=='nls')
MSEs.framed.4 <- MSEs.framed %>% filter(name=='logistic')
```


```{r all_plots}
.ylim <- c(0.95,1.2)
.ylim2 <- c(0.95,4)
.jitter <- 10
.size <- 3
.font.size <- 40

plot.0 <- plotMSEs(MSEs.framed.0, '(a) OLS', center='median', legend.position='none', y.lim=.ylim, jitter=.jitter, size = .size, font.size = .font.size)

plot.1 <- plotMSEs(MSEs.framed.1, '(b) Ridge', center='median', legend.position='none', y.lim=.ylim, jitter=.jitter, size = .size, font.size = .font.size)

plot.3 <- plotMSEs(MSEs.framed.3, '(c) NLS', center='median', legend.position='none', jitter=.jitter, y.lim=.ylim2, size = .size, font.size = .font.size)

plot.4 <- plotMSEs(MSEs.framed.4, '(d) Logistic', center='median', legend.position='none', jitter=.jitter, y.lim=.ylim2, size = .size, font.size = .font.size)

grid.arrange(plot.0, plot.1, plot.3, plot.4, ncol=2)
```


```{r export plot}
directory <- "~/workspace/ParalSimulate/output/"
the.file <-paste(directory, "classic_asymptotics_%d.pdf", sep='')
pdf(file=the.file, onefile = FALSE, paper = "special", width=8, height=8)

plot.0 <- plot.0 +
  theme(legend.position=c(0.85, 0.75), legend.key.size=unit(5,"mm"))

grid.arrange(plot.0, plot.1, plot.3, plot.4, ncol=2)
plot.0
plot.1
plot.3
plot.4
dev.off()
```



