---
title: "Fix kapa (high dim)"
author: "Jonathan Rosenblatt"
date: "13/1/2014"
output: html_document
---

## Initializing and testing
```{r Initializing}
library(InformationAndInference)
.m <- c(1e1, 2e1, 4e1, 1e2)
.kappa <- 0.2
.n <- seq(4e1, 1e3, length.out=6)
.sigma <- 1e1
.ylim <- c(1,4)
```



## OLS
```{r OLS testing}
configurations <- makeConfiguration_fixKappa(reps = 2e1, m = c(5e0, 5e1), n = c(1.5e2, 1e3) , kappa = 0.1, model = my.ols, link = identity, sigma = 1e1, beta.maker = makeBetasRandom, beta.star.maker = BetaStarIdentity, data.maker = makeRegressionData, truth.fun = truthOLS) 
configurations %>% dim
.MSEs.0 <- apply(configurations, 1, replicateMSE)
MSEs.framed.0 <- frameMSEs_fixKappa(.MSEs.0, configurations)
MSEs.framed.0 %>% select(n, p, m, average, truth)
plotMSEs_fixKappa(MSEs.framed.0, 'test', y.lim=c(0.9,2))
```


```{r  OLS run}
configurations.00 <- makeConfiguration_fixKappa(
  reps = 5e1, 
  m = .m, 
  n = .n , 
  kappa = .kappa, 
  lambda = NA, 
  sigma = .sigma, 
  model = my.ols, link = identity, beta.maker = makeBetasDeterministic, 
  beta.star.maker = BetaStarIdentity, data.maker = makeRegressionData,
  truth.fun=truthOLS) 

# cl <- makeCluster(30)
# clusterEvalQ(cl, library(InformationAndInference))
MSEs.00 <- parApply(cl, configurations.00, 1, replicateMSE)
# stopCluster(cl)
```


```{r OLS plot, eval=FALSE, echo=FALSE}
MSEs.framed.00 <- frameMSEs_fixKappa(MSEs.00, configurations.00)
plotMSEs_fixKappa(MSEs.framed.00, 'OLS', legend.position='right', y.lim=.ylim)
```

```{r OLS saving}
save(MSEs.00, configurations.00, file='RData/MSEs.00.1.RData')
```



## Ridge
```{r Ridge testing}
configurations.1 <- makeConfiguration_fixKappa(
  reps = 2e1, m = c(1e1,1e2), n = c(1.5e2, 5e2, 1e3) , kappa = 0.3, 
  lambda = c(2e0, 2e1), model = my.ridge, 
  link = identity, sigma = 1e1, 
  beta.maker = makeBetasRandom, beta.star.maker = BetaStarRidge, 
  data.maker = makeRegressionData) 
configurations.1 %>% dim

# .MSEs.1 <- apply(configurations.1, 1, replicateMSE)
cl <- makeCluster(min(30, nrow(configurations.1)))
clusterEvalQ(cl, library(InformationAndInference))
.MSEs.1 <- parApply(cl, configurations.1, 1, replicateMSE)
stopCluster(cl)

MSEs.framed.1 <- frameMSEs_fixKappa(.MSEs.1, configurations.1)
MSEs.framed.1 %>% select(n, p, m, average, truth)
plotMSEs_fixKappa(MSEs.framed.1, 'test', y.lim=c(0.9,2), legend.position='right')
```



```{r ridge run}
configurations.10 <- makeConfiguration_fixKappa(
  reps = 5e1,
  m = .m, 
  kappa = .kappa, 
  n = .n, 
  lambda=2,
  model = my.ridge, link = identity, sigma = .sigma, 
  beta.maker = makeBetasDeterministic, beta.star.maker = BetaStarRidge,
  data.maker=makeRegressionData) 

# cl <- makeCluster(min(30, nrow(configurations.10)))
# clusterEvalQ(cl, library(InformationAndInference))
MSEs.10 <- parApply(cl, configurations.10, 1, replicateMSE)
# stopCluster(cl)
```


```{r Ridge plot, eval=FALSE, echo=FALSE}
MSEs.framed.10 <- frameMSEs_fixKappa(MSEs.10, configurations.10)
plot.10 <- plotMSEs_fixKappa(MSEs.framed.10, 'Ridge', legend.position='right', y.lim=.ylim)
plot.10
```


```{r Ridge saving}
save(MSEs.10, configurations.10, file='RData/MSEs.10.RData')
```




## Non Linear
```{r nonlinear test}
configurations <- makeConfiguration_fixKappa(reps = 1e1, m = c(5e0, 2e1), kappa = 0.5, n = c(2e2, 4e2), lambda = NA, model = my.log.link, link = exp, sigma = 1e0, beta.maker = makeBetasRandom, beta.star.maker = BetaStarIdentity, data.maker = makeRegressionData) 
configurations %>% dim
.MSEs.3 <- apply(configurations, 1, replicateMSE)
# cl <- makeCluster(3)
# clusterEvalQ(cl, library(InformationAndInference))
# .MSEs.3 <- parApply(cl, configurations, 1, replicateMSE)
# stopCluster(cl)
MSEs.framed.3 <- frameMSEs_fixKappa(.MSEs.3, configurations)
MSEs.framed.3 %>% select(n, average, p, m, kappa)
plotMSEs_fixKappa(MSEs.framed.3, 'test', y.lim=c(0.8,20))
```


```{r nonlinear run}
configurations.30 <- makeConfiguration_fixKappa(
  reps = 5e1, 
  m = .m, 
  kappa = .kappa, 
  n = .n, 
  lambda = NA, 
  model = my.log.link, link = exp, sigma = 1, 
  beta.maker = makeBetasRandom, beta.star.maker = BetaStarIdentity, 
  data.maker=makeRegressionData) 
                  
cl <- makeCluster(min(30, nrow(configurations.30)))
clusterEvalQ(cl, library(InformationAndInference))
MSEs.30 <- parApply(cl, configurations.30, 1, replicateMSE)
# stopCluster(cl)
```


```{r nonlinear plot, eval=FALSE, echo=FALSE}
# load(file='RData/MSEs.30.RData')
MSEs.framed.30 <- frameMSEs_fixKappa(MSEs.30, configurations.30)
MSEs.framed.30 %>% select(n, average) %>% head
plot.30 <- plotMSEs_fixKappa(MSEs.framed.30, 'Non-Linear Least Squares', legend.position='right', y.lim=.ylim )
plot.30
```

```{r nonlinear save}
save(MSEs.30, configurations.30, file='RData/MSEs.30.RData')
```


## Logistic Regression
```{r logistic test}
configurations <- makeConfiguration_fixKappa(
  reps = 2e1, 
  m = c(5e0, 2e1), 
  n = seq(1e2, 5e2, length.out = 2), 
  kappa=c(0.1,0.2,0.3), 
  model = my.logistic, 
  link = sigmoid, sigma = NA, 
  beta.maker =makeBetasRandom, beta.star.maker = BetaStarIdentity, 
  data.maker = makeClassificationData) 
configurations %>% dim

# .MSEs.4 <- apply(configurations, 1, replicateMSE)
# cl <- makeCluster(3)
# clusterEvalQ(cl, library(InformationAndInference))
.MSEs.4 <- parApply(cl, configurations, 1, replicateMSE)
# stopCluster(cl)
MSEs.framed.4 <- frameMSEs_fixKappa(.MSEs.4, configurations)
MSEs.framed.4 %>% select(n, p, m, N, kappa, average)
MSEs.framed.4 %>%  filter(kappa==0.3) %>%
  plotMSEs_fixKappa('test', y.lim=c(1,20), robust = FALSE)
```



```{r logistic run}
configurations.40<- makeConfiguration_fixKappa(
  reps = 1e2, 
  m = .m, 
  kappa = .kappa, 
  n = .n, 
  model = my.logistic, link = sigmoid, sigma = .sigma, 
  beta.maker = makeBetasRandom, beta.star.maker = BetaStarIdentity, 
  data.maker = makeClassificationData) 

# cl <- makeCluster(min(30, nrow(configurations.4)))
# clusterEvalQ(cl, library(InformationAndInference))
MSEs.40 <- parApply(cl, configurations.40, 1, replicateMSE)
# stopCluster(cl)
```

```{r logistic plot, eval=FALSE, echo=FALSE}
MSEs.framed.40 <- frameMSEs_fixKappa(MSEs.40, configurations.40)
plot.40 <- plotMSEs_fixKappa(MSEs.framed.40, 'Logistic', legend.position='right', y.lim=.ylim)
plot.40
```

```{r logistic save}
save(MSEs.40, configurations.40, file='RData/MSEs.40.RData')
```
TODO: 
- Why is logistic regression so good? Probably easy kappa. 
- What is the effect of lambda in Ridge? (minor)

```{r all_plots}
load(file = 'RData/MSEs.00.RData');load(file = 'RData/MSEs.10.RData');load(file = 'RData/MSEs.30.RData');load(file = 'RData/MSEs.40.RData')

plot.00 <- plotMSEs_fixKappa(MSEs.framed.00, '(a) OLS', legend.position='none', y.lim=.ylim)
plot.10 <- plotMSEs_fixKappa(MSEs.framed.10, '(b) Ridge', legend.position='none', y.lim=.ylim)
plot.30 <- plotMSEs_fixKappa(MSEs.framed.30, '(c) Non-Linear Least Squares', legend.position='none', y.lim=.ylim )
plot.40 <- plotMSEs_fixKappa(MSEs.framed.40, '(d) Logistic', legend.position='none', y.lim=.ylim)

directory <- "~/workspace/ParalSimulate/output/"
the.file <-paste(directory, "highdim_asymptotics_1.pdf", sep='')
pdf(file=the.file, onefile = FALSE, paper = "special", width=8, height=8)
grid.arrange(plot.00, plot.10, plot.30, plot.40, ncol=2)
dev.off()
```


